export const MOCK_EVENTS = [
  {
    id: 1,
    title: 'Global Tech Conference 2026',
    category: 'Conference',
    location: 'San Francisco, CA',
    startDate: '2026-09-15T09:00:00Z',
    endDate: '2026-09-17T18:00:00Z',
    format: 'Offline',
    type: 'Paid',
    maxAttendees: 5000,
    registered: 3450,
    volunteersRequired: 100,
    status: 'Published',
    description: 'The largest gathering of tech enthusiasts exploring AI, Web3, and future computing. Join industry leaders, innovative startups, and tech professionals for three days of keynotes, hands-on workshops, and networking opportunities that will shape the future of technology.',
  },
  {
    id: 2,
    title: 'Intro to React Native',
    category: 'Workshop',
    location: 'Zoom',
    startDate: '2026-08-10T10:00:00Z',
    endDate: '2026-08-10T14:00:00Z',
    format: 'Online',
    type: 'Free',
    maxAttendees: 200,
    registered: 200,
    volunteersRequired: 5,
    status: 'Published',
    description: 'A beginner-friendly workshop on building cross-platform mobile apps. Learn how to leverage your existing React knowledge to build native applications for iOS and Android. Topics include components, styling, navigation, and API integration.',
  },
  {
    id: 3,
    title: 'University Hackathon Fall',
    category: 'Hackathon',
    location: 'Main Campus Library',
    startDate: '2026-10-01T18:00:00Z',
    endDate: '2026-10-03T18:00:00Z',
    format: 'Offline',
    type: 'Free',
    maxAttendees: 300,
    registered: 120,
    volunteersRequired: 30,
    status: 'Published',
    description: '48-hour coding marathon to solve campus problems. Form a team, pitch ideas, and build functional prototypes. Mentors from top tech companies will be available to help you overcome technical hurdles. Free food and swag for all participants!',
  },
  {
    id: 4,
    title: 'Digital Marketing Seminar',
    category: 'Seminar',
    location: 'Google Meet',
    startDate: '2026-08-20T14:00:00Z',
    endDate: '2026-08-20T16:00:00Z',
    format: 'Online',
    type: 'Paid',
    maxAttendees: 500,
    registered: 410,
    volunteersRequired: 2,
    status: 'Published',
    description: 'Learn modern marketing strategies from industry experts. We will cover SEO optimization, content strategy, social media algorithms, and data analytics. Perfect for marketing professionals looking to update their skill set.',
  },
  {
    id: 5,
    title: 'Campus Cultural Fest',
    category: 'Festival',
    location: 'Central Stadium',
    startDate: '2026-11-05T10:00:00Z',
    endDate: '2026-11-07T22:00:00Z',
    format: 'Offline',
    type: 'Free',
    maxAttendees: 10000,
    registered: 4500,
    volunteersRequired: 200,
    status: 'Published',
    description: 'Annual cultural festival featuring music, dance, and art. Experience diverse cultures through performances, food stalls, and interactive exhibitions. The grand finale includes a live concert by a renowned guest artist.',
  }
];
